appName: lychee
timezone: America/New_York
dbConnection: sqlite
host: lychee.example.com

ingress:
  className: traefik
  #annotations:
    #cert-manager.io/cluster-issuer: letsencrypt

deployment:
  imagePullPolicy: IfNotPresent
  image: lycheeorg/lychee
  strategy: Recreate
  annotations:
  nodeSelector:
  tag:

uploads:
  size: 1500Gi
  storageClass: longhorn

conf:
  size: 5Gi
  storageClass: longhorn

admin:
  username: markiemark
  password: w#ikNRip7WqeQeTq1p

additionalEnvs: []
secretRefs: []
